CLASS_ORDER = ["Fighter", "Barbarian", "Rogue", "Ranger", "Paladin", "Cleric", "Druid", "Wizard"]

CLASSES = {
    "Fighter": {
        "class_id": "Fighter",
        "name": "Fighter",
        "role": "Frontline combat specialist focused on weapon mastery, battlefield control, and durability.",
        "ability_scores": {"STR": 16, "DEX": 13, "CON": 15, "INT": 11, "WIS": 13, "CHA": 9},
        "hp_max": 12,
        "armor_class": 18,
        "speed": 30,
        "class_prompt_guidance": [
            "Use Cleave when two enemies are alive and the GM wants a multi-target strike. Preferred call: send exactly one resolve_action entry with ability CLEAVE targeting one living enemy; the backend will choose a second different living enemy and resolve both strikes. Alternative call: send exactly two LONGSWORD attacks against two different targets. Never send more than one CLEAVE entry in the same turn.",
        ],
        "features": ["Cleave", "Fighting Style - Protection", "Second Wind"],
        "weapons": ["Longsword", "Handaxe"],
        "attack_profiles": [
            {"name": "Longsword", "attack_formula": "1d20+5", "damage_formula": "1d8+3", "damage_type": "slashing", "range": "melee"},
            {"name": "Handaxe", "attack_formula": "1d20+5", "damage_formula": "1d6+3", "damage_type": "slashing", "range": "melee or thrown"},
        ],
        "inventory": ["Chain mail", "Shield", "Longsword", "Handaxe x2", "Explorer's pack"],
        "doctrine": [
            "Hold the frontline.",
            "Protect weaker allies.",
            "Maintain control of enemy positioning.",
            "Sustain through longer fights.",
        ],
    },
    "Barbarian": {
        "class_id": "Barbarian",
        "name": "Barbarian",
        "role": "Shock trooper who absorbs damage and delivers devastating melee attacks.",
        "ability_scores": {"STR": 16, "DEX": 14, "CON": 15, "INT": 9, "WIS": 13, "CHA": 11},
        "hp_max": 15,
        "armor_class": 15,
        "speed": 30,
        "class_prompt_guidance": [
            "Use Rage only in combat. Rage is a bonus action with 2 uses per adventure; call resolve_action with RAGE targeting yourself. While active for the combat, your attacks gain +2 damage and incoming damage is halved by the backend.",
        ],
        "features": ["Rage", "Unarmored Defense"],
        "weapons": ["Greataxe", "Handaxes"],
        "attack_profiles": [
            {"name": "Greataxe", "attack_formula": "1d20+5", "damage_formula": "1d12+3", "damage_type": "slashing", "range": "melee"},
            {"name": "Handaxe", "attack_formula": "1d20+5", "damage_formula": "1d6+3", "damage_type": "slashing", "range": "melee or thrown"},
        ],
        "inventory": ["Greataxe", "Handaxe x2", "Explorer's pack", "Javelins x4"],
        "doctrine": ["Charge dangerous enemies.", "Draw enemy attention.", "Break enemy lines through aggression."],
    },
    "Rogue": {
        "class_id": "Rogue",
        "name": "Rogue",
        "role": "Precision striker specializing in stealth, positioning, and exploiting enemy vulnerabilities.",
        "ability_scores": {"STR": 9, "DEX": 16, "CON": 13, "INT": 15, "WIS": 11, "CHA": 14},
        "hp_max": 9,
        "armor_class": 15,
        "speed": 30,
        "class_prompt_guidance": [
            "Skill Expert is passive: all skill checks roll with advantage in the backend.",
            "Sneak Attack is passive: when you attack an enemy already damaged in the same combat, backend doubles your rolled damage once on that turn. Do not invent extra sneak attack dice.",
        ],
        "features": ["Sneak Attack", "Skill Expert", "Thieves' Cant"],
        "weapons": ["Rapier", "Shortbow"],
        "attack_profiles": [
            {"name": "Rapier", "attack_formula": "1d20+5", "damage_formula": "1d8+3", "damage_type": "piercing", "range": "melee"},
            {"name": "Shortbow", "attack_formula": "1d20+5", "damage_formula": "1d6+3", "damage_type": "piercing", "range": "ranged"},
        ],
        "inventory": ["Leather armor", "Rapier", "Shortbow", "Arrows x20", "Thieves' tools", "Burglar pack"],
        "doctrine": ["Avoid direct confrontation.", "Strike distracted enemies.", "Exploit positioning."],
    },
    "Ranger": {
        "class_id": "Ranger",
        "name": "Ranger",
        "role": "Mobile tracker and ranged skirmisher who controls space through awareness and mobility.",
        "ability_scores": {"STR": 13, "DEX": 16, "CON": 14, "INT": 11, "WIS": 15, "CHA": 9},
        "hp_max": 12,
        "armor_class": 15,
        "speed": 30,
        "class_prompt_guidance": [
            "Use Double Nock when the GM wants focused ranged pressure. Preferred call: send exactly one resolve_action entry with ability DOUBLE_NOCK targeting one living enemy; the backend will resolve two separate arrow attacks against that same target. Alternative call: send exactly two LONGBOW attacks against the same target. Never send more than one DOUBLE_NOCK entry in the same turn.",
        ],
        "features": ["Double Nock", "Favored Enemy", "Natural Explorer"],
        "weapons": ["Longbow", "Shortswords"],
        "attack_profiles": [
            {"name": "Longbow", "attack_formula": "1d20+5", "damage_formula": "1d8+3", "damage_type": "piercing", "range": "ranged"},
            {"name": "Shortsword", "attack_formula": "1d20+5", "damage_formula": "1d6+3", "damage_type": "piercing", "range": "melee"},
        ],
        "inventory": ["Scale mail", "Longbow", "Arrows x20", "Shortswords x2", "Explorer's pack"],
        "doctrine": ["Fight at range when possible.", "Use terrain advantage.", "Track enemies and scout."],
    },
    "Paladin": {
        "class_id": "Paladin",
        "name": "Paladin",
        "role": "Armored champion who protects allies and destroys powerful enemies through divine strength.",
        "ability_scores": {"STR": 16, "DEX": 11, "CON": 15, "INT": 9, "WIS": 13, "CHA": 14},
        "hp_max": 12,
        "armor_class": 18,
        "speed": 30,
        "class_prompt_guidance": [
            "Smite is once per combat: call resolve_action with SMITE before attacking; the backend rolls a normal Longsword attack and adds 2d8 damage on hit.",
            "Lay on Hands is once per combat and only in combat: call resolve_action with LAY_ON_HANDS targeting an injured player to restore 5 HP.",
        ],
        "features": ["Smite", "Lay on Hands", "Divine Sense"],
        "weapons": ["Longsword", "Javelins"],
        "attack_profiles": [
            {"name": "Longsword", "attack_formula": "1d20+5", "damage_formula": "1d8+3", "damage_type": "slashing", "range": "melee"},
            {"name": "Javelin", "attack_formula": "1d20+5", "damage_formula": "1d6+3", "damage_type": "piercing", "range": "melee or thrown"},
        ],
        "inventory": ["Chain mail", "Shield", "Longsword", "Javelins x5", "Explorer's pack", "Holy symbol"],
        "doctrine": ["Stand beside the fighter in melee.", "Protect allies.", "Deliver decisive blows."],
    },
    "Cleric": {
        "class_id": "Cleric",
        "name": "Cleric",
        "role": "Divine support who heals allies, enhances party capability, and maintains battlefield stability.",
        "class_prompt_guidance": [
            "Use healing magic with restraint and purpose.",
            "As a default tactical rule, only use healing spells on allies who are below half of their maximum HP, unless the GM gives a specific reason to heal someone else.",
            "Use the MK5 Spell MP system: Cure Wounds and Bless each cost 1 MP, you start with 6 MP, long rests and Potion of Spell Restore recover MP, and you should warn the GM when you are down to 1 MP.",
            "Bless is combat-only and affects the party for the whole combat: call resolve_action with BLESS. The backend applies +2 to attack rolls and damage.",
        ],
        "ability_scores": {"STR": 13, "DEX": 11, "CON": 14, "INT": 10, "WIS": 16, "CHA": 15},
        "hp_max": 10,
        "mp_max": 6,
        "armor_class": 18,
        "speed": 30,
        "features": ["Spellcasting", "Bless", "Divine Domain"],
        "weapons": ["Mace"],
        "attack_profiles": [
            {"name": "Mace", "attack_formula": "1d20+3", "damage_formula": "1d6+1", "damage_type": "bludgeoning", "range": "melee"},
        ],
        "inventory": ["Chain mail", "Shield", "Mace", "Holy symbol", "Priest pack"],
        "doctrine": ["Sustain the party.", "Heal injured allies.", "Maintain buffs."],
    },
    "Druid": {
        "class_id": "Druid",
        "name": "Druid",
        "role": "Nature caster who controls terrain and adapts between support, control, and offense.",
        "class_prompt_guidance": [
            "Use healing magic with restraint and purpose.",
            "As a default tactical rule, only use healing spells on allies who are below half of their maximum HP, unless the GM gives a specific reason to heal someone else.",
            "Use the MK5 Spell MP system: Cure Wounds and Thunderwave each cost 1 MP, you start with 6 MP, long rests and Potion of Spell Restore recover MP, and you should warn the GM when you are down to 1 MP.",
            "Thunderwave attacks all living Opposition targets: call resolve_action with THUNDERWAVE. The backend rolls separately for each target and applies 2d8 damage on each hit.",
        ],
        "ability_scores": {"STR": 11, "DEX": 13, "CON": 14, "INT": 10, "WIS": 16, "CHA": 15},
        "hp_max": 10,
        "mp_max": 6,
        "armor_class": 14,
        "speed": 30,
        "features": ["Spellcasting", "Thunderwave", "Druidic"],
        "weapons": ["Scimitar", "Quarterstaff"],
        "attack_profiles": [
            {"name": "Scimitar", "attack_formula": "1d20+3", "damage_formula": "1d6+1", "damage_type": "slashing", "range": "melee"},
            {"name": "Quarterstaff", "attack_formula": "1d20+2", "damage_formula": "1d6", "damage_type": "bludgeoning", "range": "melee"},
        ],
        "inventory": ["Hide armor", "Scimitar", "Druidic focus", "Explorer's pack"],
        "doctrine": ["Control battlefield space.", "Support allies.", "Disrupt enemy movement."],
    },
    "Wizard": {
        "class_id": "Wizard",
        "name": "Wizard",
        "role": "Arcane strategist who manipulates the battlefield through versatile spells and tactical control.",
        "class_prompt_guidance": [
            "Use the MK5 Spell MP system: Magic Missile and Burning Hands each cost 1 MP, Firebolt costs 0 MP, you start with 6 MP, long rests and Potion of Spell Restore recover MP, and you should warn the GM when you are down to 1 MP.",
            "Firebolt is a reliable free attack spell: call resolve_action with FIREBOLT against one target. The backend rolls 1d20+10 to hit and 1d10 fire damage.",
            "Burning Hands attacks all living Opposition targets: call resolve_action with BURNING_HANDS. The backend rolls separately for each target and applies 3d6 fire damage on each hit.",
        ],
        "ability_scores": {"STR": 9, "DEX": 14, "CON": 13, "INT": 16, "WIS": 12, "CHA": 11},
        "hp_max": 8,
        "mp_max": 6,
        "armor_class": 12,
        "speed": 30,
        "features": ["Spellcasting", "Firebolt", "Burning Hands", "Arcane Recovery"],
        "weapons": ["Quarterstaff"],
        "attack_profiles": [
            {"name": "Quarterstaff", "attack_formula": "1d20+1", "damage_formula": "1d6-1", "damage_type": "bludgeoning", "range": "melee"},
        ],
        "inventory": ["Spellbook", "Quarterstaff", "Component pouch", "Scholar pack"],
        "doctrine": ["Avoid direct melee combat.", "Control the battlefield.", "Use spells strategically."],
    },
}
