from ...prompt_loader import load_player_persona

PLAYER_ORDER = ["Joe", "Annie", "Tammey", "Rick", "Beau", "Sam", "Tom", "Jannet"]

PLAYERS = {
    "Joe": {
        "player_id": "Joe",
        "name": "Joe",
        "archetype": "Orphan",
        "gender": "Male",
        "race": "Dwarf",
        "irl_job": "Social worker",
        "keywords": ["Protective", "Cautious", "Compassionate"],
        "display_text": load_player_persona("Joe"),
    },
    "Annie": {
        "player_id": "Annie",
        "name": "Annie",
        "archetype": "Hero",
        "gender": "Female",
        "race": "Elf",
        "irl_job": "Retail",
        "keywords": ["Bold", "Inspiring", "Dramatic"],
        "display_text": load_player_persona("Annie"),
    },
    "Tammey": {
        "player_id": "Tammey",
        "name": "Tammey",
        "archetype": "Caregiver",
        "gender": "Female",
        "race": "Half-Elf",
        "irl_job": "Nurse",
        "keywords": ["Supportive", "Steady", "Empathetic"],
        "display_text": load_player_persona("Tammey"),
    },
    "Rick": {
        "player_id": "Rick",
        "name": "Rick",
        "archetype": "Explorer",
        "gender": "Male",
        "race": "Human",
        "irl_job": "Park Ranger",
        "keywords": ["Curious", "Practical", "Observant"],
        "display_text": load_player_persona("Rick"),
    },
    "Beau": {
        "player_id": "Beau",
        "name": "Beau",
        "archetype": "Rebel",
        "gender": "non-binary",
        "race": "Elf",
        "irl_job": "Human Resources",
        "keywords": ["Defiant", "Clever", "Disruptive"],
        "display_text": load_player_persona("Beau"),
    },
    "Sam": {
        "player_id": "Sam",
        "name": "Sam",
        "archetype": "Jester",
        "gender": "Male",
        "race": "Gnome",
        "irl_job": "Customer Service",
        "keywords": ["Playful", "Expressive", "Unpredictable"],
        "display_text": load_player_persona("Sam"),
    },
    "Tom": {
        "player_id": "Tom",
        "name": "Tom",
        "archetype": "Magician",
        "gender": "Male",
        "race": "Human",
        "irl_job": "Engineer",
        "keywords": ["Analytical", "Strategic", "Precise"],
        "display_text": load_player_persona("Tom"),
    },
    "Jannet": {
        "player_id": "Jannet",
        "name": "Jannet",
        "archetype": "Ruler",
        "gender": "Female",
        "race": "Human",
        "irl_job": "School Principle",
        "keywords": ["Decisive", "Organized", "Authoritative"],
        "display_text": load_player_persona("Jannet"),
    },
}
